#pragma kernel VolumeLightingRayMarch

#define _CLUSTERED_LIGHTING
#pragma multi_compile_fragment _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE//_MAIN_LIGHT_SHADOWS_SCREEN
#define _ADDITIONAL_LIGHT_SHADOWS
#define _SHADOWS_SOFT _SHADOWS_SOFT_LOW _SHADOWS_SOFT_MEDIUM _SHADOWS_SOFT_HIGH

#pragma multi_compile _ _DIRECTIONAL_VOLUME_LIGHT
#pragma multi_compile _ _ADDITIONAL_VOLUME_LIGHTS

#include "Packages/roxamirpcore/Shaders/Core/Common.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Input.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"

RWTexture2D<half3> _VolumeLightingTexture;

float4 _texelSize;

float4 _volumeLightingParams;
#define _stepSize _volumeLightingParams.x
#define _maxStep _volumeLightingParams.y
#define _maxRayLength _volumeLightingParams.z
#define _randomStrength _volumeLightingParams.w

half _VolumeAdditionalLightDistancePower;

half _VolumeLightingDensity;

float4 _VolumeLightingFade;
#define _fadeStart _VolumeLightingFade.x
#define _fadeLength _VolumeLightingFade.y

// Generate random value between -1 and 1
float Random(uint2 id)
{
    return Hash21(id) * 2.0 - 1.0;
}

float SampleShadow(float3 positionWS)
{
    float4 shadowCoord = TransformWorldToShadowCoord(positionWS);
    return MainLightRealtimeShadow(shadowCoord);
}

// Matches Unity Vanilla HINT_NICE_QUALITY attenuation
// Attenuation smoothly decreases to light range.
float m_DistanceAttenuation(float distanceSqr, half2 distanceAttenuation)
{
    // We use a shared distance attenuation for additional directional and puctual lights
    // for directional lights attenuation will be 1
    float lightAtten = rcp(distanceSqr);
    float2 distanceAttenuationFloat = float2(distanceAttenuation);

    // Use the smoothing factor also used in the Unity lightmapper.
    half factor = half(pow(distanceSqr * distanceAttenuationFloat.x, max(HALF_MIN, _VolumeAdditionalLightDistancePower)));
    half smoothFactor = saturate(half(1.0) - factor * factor);
    smoothFactor = smoothFactor * smoothFactor;

    return lightAtten * smoothFactor;
}

// Fills a light struct given a perObjectLightIndex
Light m_GetAdditionalPerObjectLight(int perObjectLightIndex, float3 positionWS)
{
    // Abstraction over Light input constants
    #if USE_STRUCTURED_BUFFER_FOR_LIGHT_DATA
    float4 lightPositionWS = _AdditionalLightsBuffer[perObjectLightIndex].position;
    half3 color = _AdditionalLightsBuffer[perObjectLightIndex].color.rgb;
    half4 distanceAndSpotAttenuation = _AdditionalLightsBuffer[perObjectLightIndex].attenuation;
    half4 spotDirection = _AdditionalLightsBuffer[perObjectLightIndex].spotDirection;
    uint lightLayerMask = _AdditionalLightsBuffer[perObjectLightIndex].layerMask;
    #else
    float4 lightPositionWS = _AdditionalLightsPosition[perObjectLightIndex];
    half3 color = _AdditionalLightsColor[perObjectLightIndex].rgb;
    half4 distanceAndSpotAttenuation = _AdditionalLightsAttenuation[perObjectLightIndex];
    half4 spotDirection = _AdditionalLightsSpotDir[perObjectLightIndex];
    uint lightLayerMask = asuint(_AdditionalLightsLayerMasks[perObjectLightIndex]);
    #endif

    // Directional lights store direction in lightPosition.xyz and have .w set to 0.0.
    // This way the following code will work for both directional and punctual lights.
    float3 lightVector = lightPositionWS.xyz - positionWS * lightPositionWS.w;
    float distanceSqr = max(dot(lightVector, lightVector), HALF_MIN);

    half3 lightDirection = half3(lightVector * rsqrt(distanceSqr));
    // full-float precision required on some platforms
    float attenuation = m_DistanceAttenuation(distanceSqr, distanceAndSpotAttenuation.xy) * AngleAttenuation(spotDirection.xyz, lightDirection, distanceAndSpotAttenuation.zw);

    Light light;
    light.direction = lightDirection;
    light.distanceAttenuation = attenuation;
    light.shadowAttenuation = 1.0; // This value can later be overridden in GetAdditionalLight(uint i, float3 positionWS, half4 shadowMask)
    light.color = color;
    light.layerMask = lightLayerMask;

    return light;
}

Light m_GetAdditionalLight(uint i, float3 positionWS)
{
    #if USE_CLUSTERED_LIGHTING
    int lightIndex = i;
    #else
    int lightIndex = GetPerObjectLightIndex(i);
    #endif
    return m_GetAdditionalPerObjectLight(lightIndex, positionWS);
}

float3 GetVolumeAdditonalLightColor(int lightIndex, float3 positionWS)
{
    Light light = GetAdditionalLight(lightIndex, positionWS);
    half4 shadowMask = 0;
    half4 occlusionProbeChannels = 0;
    light.shadowAttenuation = AdditionalLightShadow(lightIndex, positionWS, light.direction, shadowMask, occlusionProbeChannels);

    return light.color * light.shadowAttenuation * min(light.distanceAttenuation, 5);
}

[numthreads(8,8,1)]
void VolumeLightingRayMarch (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)_texelSize.x || id.y >= (uint)_texelSize.y)
    {
        return;
    }
    
    float2 screenSpaceUV = id.xy * _texelSize.zw;
    float depth = _CameraDepthTexture.SampleLevel(sampler_CameraDepthTexture, screenSpaceUV, 1).x;
    
    float3 positionWS = CalculateDepthToPositionWS(depth, screenSpaceUV);
    float3 cameraWS = _WorldSpaceCameraPos.xyz;
    float3 rayVec = positionWS - cameraWS;
    
    float3 rayDir = normalize(rayVec);
    float3 rayStart = cameraWS;
    // rayStart += _fadeStart * rayDir;
    float rayMaxLength = min(length(positionWS - cameraWS), _maxRayLength);
    
    #ifdef _DIRECTIONAL_VOLUME_LIGHT
        Light mainLight = GetMainLight();
        half3 lightColor = mainLight.color;
    #endif

    float rayLength = 0;
    float3 volumeLightingColor = 0;

    InputData inputData = (InputData) 0;
    inputData.normalizedScreenSpaceUV = screenSpaceUV;
    inputData.positionWS = rayStart;

    UNITY_LOOP
    for(int j = 0 ; j < _maxStep ; j++)
    {
        rayLength += _stepSize * j;
        if(rayLength > rayMaxLength)
        {
            break;
        }
        
        float3 rayPositionWS = rayStart + rayDir * rayLength;
        inputData.positionWS = rayPositionWS;
        
        // Add random jittering in three directions
        if (_randomStrength > 0)
        {
            // Generate independent random offsets for X, Y, Z axes
            float3 randomOffset = float3(
                Random(id.xy + uint2(j, 0)),
                Random(id.xy + uint2(0, j)),
                Random(id.xy + uint2(j, j))
            ) * _randomStrength * _stepSize;
            
            rayPositionWS += randomOffset;
        }
        
        half3 lighting = 0;

        #ifdef _DIRECTIONAL_VOLUME_LIGHT
            lighting += SampleShadow(rayPositionWS) * lightColor;
        #endif

        #if USE_CLUSTERED_LIGHTING
        for (uint lightIndex = 0; lightIndex < min(URP_FP_DIRECTIONAL_LIGHTS_COUNT, MAX_VISIBLE_LIGHTS); lightIndex++)
        {
            lighting += GetVolumeAdditonalLightColor(lightIndex, rayPositionWS);
        }
        #endif

        uint pixelLightCount = GetAdditionalLightsCount();
        LIGHT_LOOP_BEGIN(pixelLightCount)
            lighting += GetVolumeAdditonalLightColor(lightIndex, rayPositionWS);
        LIGHT_LOOP_END
        
        volumeLightingColor += lighting;
    }
    
    volumeLightingColor /= _maxStep;
    
    _VolumeLightingTexture[id.xy] = volumeLightingColor * _VolumeLightingDensity;
}